## Abstract

BACKGROUND: 
Incidence of Sudden Unexpected Infant Death in the United States has persisted at roughly the same level since the mid-2000's despite intensive prevention efforts.
Disparities in outcomes across racial/socioeconomic lines also persist.
These disparities are reflected in the spatial distribution of cases.

METHODS: 
We used geocoded medical examiner data from 2015-2019 to identify SUID cases in Cook County, IL and aggregated them to census tracts as the unit of analysis. 
We compared demographics and socioeconomic factors in tracts affected by SUID versus those unaffected.
We used social vulnerability indicators from 2014 to train a prediction model for the presence of SUID in each given tract from 2015-2019.
We fed indicators from 2020 into our model to make predictions for 2021-2025 and mapped the results.

RESULTS: 
Tracts affected by SUID exhibited higher proportions of Black residents (68% vs 4%) and lower proportions of White residents (4% vs. 46%).
Affected tracts also had higher socioeconomic vulnerability scores (median of 86th national percentile vs 50th national percentile).
Our model showed moderate accuracy on training data (AUC 76.6%).
A map of tracts in Suburban Cook County both historically affected by SUID (2015-2019) and predicted by our model to be affected in the future (2021-2025) showed clusters in the South and West regions.

CONCLUSIONS: 
Sharp racial and socioeconomic disparities in SUID incidence persisted within Cook County from 2015-2019.
Our model and maps identified precise regions within the county's suburbs for our local health department to target for intervention.
These communities should be closely engaged on how best to intervene within their specific contexts.