# Import and Wrangle the Data

## Dependencies

```{r}
# Load needed modules
box::use(
    dplyr[
        case_when,
        full_join, 
        glimpse, 
        mutate,
        rename,
        select
    ],
    janitor[clean_names],
    magrittr[`%>%`],
    readxl[read_xlsx],
    sf[st_set_geometry],
    sids_data_wrangling = ./modules/sids_data_wrangling,
    tibble[as_tibble]
)
```

## Initial import

First, read in the excel file that was originally shared for this project:

```{r}
raw <- 
    # Parse excel file
    read_xlsx("data/finaldataforanalysis3_220121.xlsx") %>%
    # Clean up variability in naming conventions
    clean_names()
```

## Join census tract populations

Then, import census population data:

```{r}
## This is a custom function I wrote that 
## pulls data from the TidyCensus API about
## the population count of people under five 
## years old and about spatial features 
## for each census tract. I have commented it 
## out and saved the result in an RDS file
## so as to not make a new call to the API 
## every time this script is run. You can
## inspect the function definition in the 
## modules folder of the source code.

# coords_and_pop_est <- 
#     sids_data_wrangling$get_coords_and_pop_est(raw)
# 
# saveRDS(coords_and_pop_est, "data/coords_and_pop_est.RDS")

coords_and_pop_est <- readRDS("data/coords_and_pop_est.RDS")

sids_df <- 
    # Take population estimates
    coords_and_pop_est %>%
    # Drop geospatial features
    st_set_geometry(NULL) %>%
    # Convert to tibble format
    as_tibble() %>%
    # And join to dataset
    full_join(raw) %>%
    # Add new variables
    mutate(
        # Binary variable on whether SIDS is present in a tract
        sids_present = case_when(
            count_asphyxia > 0 ~ TRUE,
            TRUE ~ FALSE
        )
    ) %>%
    # Rename variables for consistency
    rename(
        sids = count_asphyxia,
        foreign_born = pe_foreignborn,
        married_males = pe_marriedmales,
        married_females = pe_marriedfemales,
        divorced_widowed_males = pedivorcewidowedmale,
        divorced_widowed_females = pedivorcewidowedfemale,
        lt_high_school = pelessthanhighschool,
        high_school_diploma = highschooldiploma,
        some_college = somecollege,
        college_diploma = collegediploma,
        employed = percent_enployed,
        income_lt_10 = incomelt10,
        income_lt_25 = incomelt25,
        income_lt_50 = incomelt50,
        income_lt_75 = incomelt75,
        income_gt_75 = incomegt75,
        private_insurance = privateinsurance,
        public_insurance = publicinsurance,
        no_insurance = noinsurance
    )

# Preview the data
glimpse(sids_df)
```

## Save for use in other chapters

```{r}
saveRDS(sids_df, file = "data/sids_df.RDS")
```

