## Introduction

Sudden Unexpected Infant Death (SUID) exacts a severe, lasting toll on bereaved family members and society at large. At the familial level, loss of an infant may put caregivers--especially birth mothers--at heightened risk for Prolonged Grief Disorder where the process of healing and acceptance evades realization [@goldsteinGriefMothersSudden2018]. At the societal level, 20% of all post-neonatal infant deaths in the United States are ascribed to Sudden Infant Death Syndrome (SIDS), a subset of SUID [@GBDCompare].

United States health agencies define SUID as "the death of an infant younger than 1 year of age that occurs suddenly and unexpectedly". Sometimes, medical investigation identifies a cause (e.g. suffocation/entrapment related to unsafe sleep conditions), but when a full investigation does not reveal a cause, such cases are defined as SIDS [@CommonSIDSSUID].

The "Back to Sleep" campaign initiated in 1994 helped significantly reduce rates of SUID at global, national, and Illinois state levels. However, further reductions have not been achieved since the early 2000's [@shapiro-mendozaEpidemiologySuddenInfant2018; @SIDSSleepRelatedInfant]. One barrier to mortality prevention efforts has been the inequitable distribution of protective factors in different communities leading to disparate outcomes. For example, the white population of Illinois had a SUID rate of about 64 cases per 100,000 infants in 2014, while the black population had a rate of about 172 per 100,000 [@SIDSSleepRelatedInfant].

Racial inequities may be obscured on the geographic dimension when summarizing information at the country or state level, but stark contrasts emerge when disaggregating to more granular levels. This may be because historic forces of racial and socioeconomic segregation (e.g. redlining and racial covenants) were enforced at the neighborhood level [@rothsteinColorLawForgotten2017].

Proponents of precision public health argue that fine-grained characterization not only of location, but also time, demographics, risk/protective factors, and outcomes enables health service providers to intervene on behalf of communities most disparately impacted by conditions like SUID. Without precision, providers risk exacerbating inequity by bolstering resources in areas already well-supplied, while neglecting areas with highest need [@hortonOfflineDefencePrecision2018]. But precision is necessary yet not sufficient if findings are not delivered in a timely, yet accurate manner. Recent studies underscore the challenges inherent in striking such a balance [@macdonaldComparingAsphyxiaUnexplained2022].


Estimating epidemiological risk with a fine level of geographic detail allows public health departments to target their limited resources to the precise areas with highest needs, but accurate estimation presents a series of linked challenges. To illustrate, this paper considers the risk of sudden unexpected infant death in census tracts of Cook County, IL from 2015 to 2019. First, identifying cases of SUID is a labor-intensive process. By definition, a diagnosis of SUID means that an infant less than one year old died without known cause prior to medical autopsy. Historically, analysts have needed to manually review medical records in order to verify cases. If the review process takes too long, practitioners are left with stale estimates and emerging hot spots might be left unidentified. Here, we outline an automated process for querying these cases from Cook County Medical Examiner's Office records.

A second challenge is that SUID is (thankfully) a rare event and the geographic areas are small. A sizable majority of census tracts in Cook County did not observe any events of SUID from 2015-2019. If we estimate risk purely from observed data, we might naively conclude that the risk of SUID in the majority of tracts was zero, when in fact we're facing issues with detecting risk that is quite small, but not zero. Here, we use Bayesian estimation of a beta distribution to combine observed data with prior expectations to create more principled estimates.

A third challenge is we know the denominator of risk--the number of live births--for the county as a whole, but not for each individual census tract. Without a fine-grained understanding of the denominator, we cannot scale estimates of risk such that our prior expectations and observed data have similarly weighted impacts. Here we approximate the denominator using the population of children under 5 in each tract obtained from the U.S. Census.

A fourth challenge is we want to fine tune our prior expectations of risk by using knowledge of other socioeconomic factors in each census tract, which we accomplish using a nested negative binomial regression model of the expected count of SUID deaths.

A final challenge is that standard regression models treat each census tract as geographically independent from all others. Here, we incorporate autoregression techniques such that the risk in one tract can diffuse across borders to adjust the expected risk in geographically proximate tracts.

Demonstrating the cumulative value of all the solutions outlined above, this paper will map how estimations of risk change after each challenge is addressed.

### Lit Review

Possible commonalities: 
- Spatial modeling of SUID
- Any Bayesian methodologies with infant death
- Using Beta dist for modeling risk in epidemiology

@ranjanInfantMortalityDeath2022 aka "Infant mortality and death clustering at the district level in India: A Bayesian approach". Commonality in that they use Bayesian methodology, but they use a "Geoadditive Model" focused on modeling infant survival in a discrete time series. They are most focused on estimating effects from variables like spatial processes, previous infant death in family, maternal age. Their geographic unit was coarser at the district level of Indian states.