## Discussion

### Principal Results

Our process for querying data from the Cook County Medical Examiner was able to identify cases of SUID from 2015-2019 with a high degree of fidelity to those identified by the county's official registry.
We aggregated these cases to the "community" level and found that those containing a case of SUID during the study period also had subjectively higher proportions of Black residents and lower proportions of White residents. 
We built a negative binomial regression model to predict for SUID Case Counts and achieved moderate accuracy, especially within the mid-range of case counts.
As an aide for deciding where to target preventive services, we mapped communities most affected by SUID.
Our results suggested local health departments should focus prevention efforts on North and West Sides of Chicago and in the South Suburbs of Cook County.
Other institutions in other regions can adapt this analytic workflow to determine priority areas for their own jurisdictions.

### Implications

We suggest our analytic outputs be used in different ways based on their temporal context. 
Within the model training period of 2014-2019, differences in retrospective predictions and observations represent promising routes of inquiry for expanding our understanding of community-level ecological factors affecting SUID incidence.
For example, public health practitioners might consider intensive qualitative inquiry in the communities most under-predicted (like Austin and Englewood) to identify new risk factors and in communities most over-predicted (like Douglas and Grand Boulevard) to identify new protective factors.
Beyond the model training period into 2020-2025, our prospective predictions represent opportunities to anticipate shifting dynamics in the communities most affected by SUID.

Regardless of temporal context, all results from this study can be used to guide a targeted, local approach to SUID prevention.
Turman and Swigonski [@turmanChangingSystemsThat2021] proposed one framework for such an approach. 
Both high-level goals of their framework hinged on identifying specific zip codes with the highest infant mortality rates in Central Indiana.
The first goal focused on developing infrastructure in those zip codes to support healthy pregnancies and infants.
For example, they increased capacity of local early childhood education programs, which both provided childcare for mothers seeking employment and served as vehicles for education on safe sleep practices.
The second goal focused on training women from those zip codes as grass roots maternal child health leaders.
Leaders developed narrative storytelling about their experiences with infant loss and were connected with local lawmakers to advocate for policies such as garnering more financial resources for grandparents raising grandchildren.
Special attention was paid toward recruiting women leaders from marginalized, minority populations.
This framework is just as applicable to Cook County as to Central Indiana.
Many of the key institutional partners like a local Fetal Infant Mortality Review Board are already in place and could use the maps and predictions from this study to identify targeted communities most at risk.

### Comparison with Prior Work

Our findings are consistent with the broader body of research on socioeconomic demographic factors related to infant mortality.
Several other studies have also identified correlation between infant mortality and community-level factors like alcohol/drug use, education, employment, immigration, insurance, involvement of child protective services, poverty, racism, and segregation [@drakeDescriptiveGeospatialAnalysis2019; @chambersExposuresStructuralRacism2020a; @bandoliMaternalInfantEnvironmental2022; @johnsonNeighborhoodPovertyAmerican2008; @guestEcologyRaceSocioeconomic1998; @hearstEffectRacialResidential2008].
Some studies have posited direct causal relationships between ecologic factors and infant mortality, but the evidence is still equivocal.
Both Hearst et al. [@hearstEffectRacialResidential2008] and Johnson et al. [@johnsonNeighborhoodPovertyAmerican2008] used propensity score matching as a means of isolating such causal effects, the former for residential segregation on Black infant mortality and the latter for neighborhood poverty on American Indian infant mortality.
Both were unable to detect an influence, but emphasized that their inability to detect effects may have been due to limitations in size of sampling pools to achieve adequate counterfactual comparisons.
Our study does not attempt to identify causal effects and instead focuses on helping local health departments to target precise regions of their jurisdictions for intervention.

Our study advances geospatial research on SUID in three major ways.
First, we added finer detail to the available Chicago-based maps by using census tracts and "communities" as areal units, with the added benefit that these can be linked to census-derived demographics. 
Second, we added interactive capability to our maps for greater utility to practitioners wanting to explore the data first-hand.
Third, to our knowledge this is the first study to have made prospective predictions on spatial incidence of SUID, helping to anticipate changing dynamics in regions of interest. 
In comparison, Briker et al. [@brikerModifiableSleeprelatedRisk2019] performed a different, but complementary analysis of Cook County data, visualizing SUID incidence in 2015-2016 by kernel density estimation (KDE).
Relative to our method of displaying counts per "community" areal unit, KDE has the advantage of smoothing out random variation observed in the data to make clusters more apparent.
With this method, these authors also found strong clusters of SUID on the West and South Sides of Chicago.
The comparative disadvantages of this technique are the visualized kernels do not have one-to-one matches with real-world administrative boundaries and the units of intensity are less interpretable than counts.
Also, because the map in Briker et al. was not interactive, it was more difficult to ascertain specific high-risk communities.
In another study, Drake et al. [@drakeDescriptiveGeospatialAnalysis2019] used KDE to visualize SUID incidence in Harris County, TX and this approach had the same advantages and disadvantages.
Fee and Tarrell [@caitline.feeGeographicalAnalysisSudden2017] used analogous techniques to those used in our study by visualizing incidence in administrative areal units of Douglas County, NE.
These authors also were able to correlate incidence with other variables, although their variables were more relevant to individual-level risk (e.g. prenatal care and tobacco use) rather than the population-level approach used in our study.
In an older seminal study, Grimson et al. [@grimsonSearchingHierarchicalClusters1981] focused on demonstrating statistical methods for identifying geospatial clusters.
Their work is relevant to our study because the authors used SUID incidence as their example use-case, but our study was not focused on identifying statistically significant clusters and was more finely detailed on a smaller geographic scale.

### Limitations

<!-- **Validity of Data Sources:**  -->
<!-- The outcomes of our analysis--count/presence of SUID cases--were derived from data records of the Cook County Medical Examiner's Office (CCMEO).  -->
<!-- It is not feasible for CCMEO to investigate every case of death in its large urban jurisdiction. -->
<!-- According to their website, "More than 16,000 deaths are reported to the [CCMEO] annually. Of these, around 5,600 are accepted for further investigation."  -->
<!-- However, we expect extremely high coverage specifically for cases of SUID since they inherently fall within the criterion for obligatory investigation of a death happening "suddenly when in apparent good condition". -->
<!-- On the other hand, CCMEO can only investigate cases for which it is aware and it is possible that there is geospatial variability in rates of reporting--leading to systemic errors in rate estimations. -->
<!-- We expect that correction of such bias would only lead to further accentuation of trends we observe within the observed data. -->

<!-- **Intended impact on individuals and society:** -->
<!-- We built this model to guide local health departments toward priority areas of the county in need of preventive services.  -->
<!-- We used variables from the SVI dataset in an effort to bake considerations of equity and justice into the model's recommendations. -->
<!-- We also chose the threshold for predicting a positive presence of SUID so that the model would slightly favor sensitivity over specificity in order to be more inclusive of regions that might potentially benefit from services. -->
<!-- Based on its historical practices when presented with areas of geographic priority (e.g. during COVID-19 vaccination campaigns), we expect our health department to use the model recommendations as a justification for directing resources toward these communities in need, and not as an excuse to add further blame to families beset by societal disadvantages. -->

Our study has limitations.
First, a Durbin-Watson test of our model for autocorrelated residuals rejected the null hypothesis, suggesting that observations were not independent of each other.
This was at least partially due to the interconnected nature of census tracts in physical space.
Indeed, a Moran I test also rejected the null hypothesis, suggesting presence of spatial autocorrelation.
Second, our model did not account for measurement error in our covariates, which are estimated by the American Community Survey using sub-samples of the population.
Failure to account for the margins of error and for spatial autocorrelation risked introducing systematic bias into our model predictions [@bazuinHowACSGets2013].
This was likely compounded by aggregating estimates for census tracts into the "community" areal unit.
Tradeoffs to this approach are described in the Methods section.

One means of addressing these limitations would be to implement a hierarchical Bayesian model of spatial measurement error [@bernardinelliDiseaseMappingErrors1997].
We attempted to do so using the geostan R package [@connordoneganGeostanPackage], but preliminary attempts yielded warnings from the software that MCMC sampling chains did not converge--significantly raising the risk of inaccurate parameter estimates.
An additional limitation, which may have contributed to non-convergence, was that we did not have access to estimates of the denominator for incidence of SUID (the count of live-births in each tract during the study period).
The model implemented in geostan requires an "offset" denominator variable, so we used population counts of children under 5 as proxy, but this may have contributed additional imprecision that hampered the MCMC sampling algorithm's ability to converge.

A final limitation was that not enough time had passed to empirically assess our model's prospective predictions. 
Decision-makers at local health departments might be more confident in the model's performance if they could see how it fared at predicting outside of the training dataset. 
We suggest mitigating this limitation by comparing prospective predictions with retrospective observations, both of which together make a more compelling argument for risk than either piece of information alone.

### Conclusions

Cook County, IL is still beset by racial and socioeconomic disparities in SUID outcomes. 
Our process for compiling and analyzing cases will allow practitioners to more quickly address such disparities with efforts targeted to regions of the county most in need of prevention services.

