
### Test for the Presence of Clustering

A Monte-Carlo simulation of Global Moran's I test showed evidence for spatial autocorrelation of SUID counts within census tracts in the study region. 

```{r}
tar_read(global_moran)
```


### Cluster Group Assignment

```{r}
library(ClustGeo)
library(dplyr)

suid <-
    tar_read(suid) |> 
    filter(approx_suid_incidence > 0)

centroids <- st_centroid(suid)

geo_dist_mtx <- as.dist(st_distance(centroids, centroids) / max(st_distance(centroids, centroids)))

count_dist_mtx <- dist(suid$suid_count) / max(dist(suid$suid_count))

tree <- hclustgeo(count_dist_mtx)

plot(tree, hang = -1, label = FALSE)
```


```{r}
choicealpha(count_dist_mtx, geo_dist_mtx, range.alpha = seq(0, 1, 0.1), K = 3)
```


```{r}
mix_tree <- hclustgeo(count_dist_mtx, geo_dist_mtx, alpha = 0.5)

suid$incidence_geo_group <- cutree(mix_tree, k = 4)
```

```{r}
group_pal <-
    leaflet::colorFactor(
        palette = "Set1",
        levels = 1:4
    )


leaflet::leaflet(suid) |>
            # Use CartoDB's background tiles
            leaflet::addProviderTiles("CartoDB.Positron") |>
            # Center and zoom the map to Cook County
            leaflet::setView(lat = 41.816544, lng = -87.749500, zoom = 9) |>
            # Add button to enable fullscreen map
            leaflet.extras::addFullscreenControl() |>
            # Add census tract polygons colored to reflect the number of deaths
            leaflet::addPolygons(
                # No borders to the polygons, just fill
                color = "gray",
                weight = 0.25,
                opacity = 1,
                # Color according to palette above
                fillColor = ~ group_pal(incidence_geo_group),
                # Group polygons by number of deaths for use in the layer control
                group = ~ suid_count_factor,
                # Make slightly transparent
                fillOpacity = 0.5,
                label = "Click me for more details!",
                # Click on the polygon to get its ID
                popup = 
                    ~ paste0(
                        "<b>FIPS ID</b>: ", as.character(fips), "</br>",
                        "<b>SUID Count</b>: ", suid_count, " deaths</br>",
                        "<b>Total Population</b>: ", pop_total, " people</br>",
                        "<b>Population Under 5 Years Old</b>: ", pop_under_five, " children</br>",
                        "<b>Rough Incidence</b>: ", approx_suid_incidence, " deaths per 1,000 babies"
                    )
            ) |>
            #Add legend
            leaflet::addLegend(
                title = "Hierarchical Cluster Group",
                values = ~ incidence_geo_group,
                pal = group_pal,
                position = "topright"
            ) |>
            # Add ability to toggle each factor grouping on or off the map
            leaflet::addLayersControl(
                overlayGroups = c(
                    "No Deaths", 
                    "One Death", 
                    "Two Deaths", 
                    "Three Deaths", 
                    "Four Deaths", 
                    "Five Deaths", 
                    "Six+ Deaths"
                ),
                position = "topleft"
            )
```

