---
title: "Infant Asphyxiation Mortality Modeling"
author: "Daniel P. Riggins, MD"
date: "11/1/2021"
output: html_document
---

This modeling analysis will seek to predict infant asphyxiation deaths in Chicagoland census tracts using a variety of census-level predictor variables, many of which are derived from the CDC's [Social Vulnerability Index (SVI)](https://seandavi.github.io/sars2pack/reference/cdc_social_vulnerability_index.html).

# Set Up

## Load needed libraries:

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(tidymodels)
library(DataExplorer)
library(corrr)
library(vcd)
library(tidycensus)
library(sf)
tidymodels_prefer()
```

## Set pseudo-random seed for reproducibility:

```{r}
set.seed(324)
```

## Import the data:

```{r}
raw <- readxl::read_xlsx("data/finaldataforanalysis3_110221.xlsx")

glimpse(raw)
```

```{r}
tbl <- raw %>%
    mutate(
        count_Asphyxia_cat = factor(
            count_Asphyxia,
            ordered = TRUE,
            levels = c(0,1,2,3,4,5,6)
        )
    )

summary(tbl$count_Asphyxia_cat)
```

```{r}
plot_intro(tbl)
```


