---
title: "Culminating Experience Proposal"
author: "Daniel P. Hall Riggins, MD"
date: "`r format(Sys.Date())`"
bibliography: "citations.bib"
---

## Background

Sudden Unexpected Infant Death (SUID) exacts a severe, lasting toll on bereaved family members and society at large. At the familial level, loss of an infant may put caregivers--especially birth mothers--at heightened risk for Prolonged Grief Disorder where the process of healing and acceptance evades realization [@goldsteinGriefMothersSudden2018]. At the societal level, 20% of all post-neonatal infant deaths in the United States are ascribed to Sudden Infant Death Syndrome (SIDS), a subset of SUID [@GBDCompare].

United States health agencies define SUID as "the death of an infant younger than 1 year of age that occurs suddenly and unexpectedly". Sometimes, medical investigation identifies a cause (e.g. suffocation/entrapment related to unsafe sleep conditions). When a full investigation does not reveal a cause, such cases are defined as SIDS [@CommonSIDSSUID].

The "Back to Sleep" campaign initiated in 1994 helped significantly reduce rates of SUID at global, national, and Illinois state levels. However, further reductions have not been achieved since the early 2000's [@shapiro-mendozaEpidemiologySuddenInfant2018; @SIDSSleepRelatedInfant]. One barrier to mortality prevention efforts has been the inequitable distribution of protective factors in different communities leading to disparate outcomes. For example, the white population of Illinois had a SUID rate of about 64 cases per 100,000 infants in 2014, while the black population had a rate of about 172 per 100,000 [@SIDSSleepRelatedInfant].

Racial inequities may be obscured in the geographic dimension when summarizing information at the country or state level, but stark contrasts emerge when disaggregating to more granular levels. This makes sense given that historic forces of segregation (e.g. redlining and racial covenants) were enforced at the neighborhood level [@rothsteinColorLawForgotten2017].

Proponents of precision public health argue that fine-grained characterization of location, time, demographics, risk/protective factors, and outcomes enables health service providers to intervene on behalf of communities most disparately impacted by conditions like SUID. Without precision, providers risk exacerbating inequity by bolstering resources in areas already well-supplied, while neglecting areas with highest need [@hortonOfflineDefencePrecision2018]. However, precision is necessary but not sufficient if findings are not delivered in a timely, yet accurate manner. Recent studies underscore the challenges inherent in striking such a balance [@macdonaldComparingAsphyxiaUnexplained2022].


## Project Description

To fulfill requirements for my culminating experience, I will write and submit a manuscript describing efforts by Cook County Health's Center for Health Equity and Innovation (CCH CHEI) to develop tools striking a balance between precision, accuracy, and timeliness when analyzing SUID cases in our county. Our team developed a semi-automated pipeline for querying SUID data from the Cook County Medical Examiner's Office, wrangling/cleaning it, compiling it into descriptive tables, generating interactive maps, and modeling its associations with census-tract level socioeconomic factors.

In brief, data from CCMEO was ingested into CHEI's data warehouse. Cases of SUID were inferred and drawn from the data via filtering rules in a SQL query. Cases captured by query were reviewed for accuracy by collaborators at the local, CDC-funded, SUID Case Registry for Cook County. 

There forward, all steps in the analytic pipeline were orchestrated by an R programming language package called "targets". The package specifies any data source, intermediate state, or final product as a target. The transformations between each target are encapsulated in R functions. The package tracks whenever a source target or function is modified and refreshes all targets downstream from the change. Such a pipeline enables greater efficiency and reproducibility of analysis.

Data wrangling/cleaning were performed predominantly with the "tidyverse" suite of R packages. Tables were generated with the R package "gt" and its derivative "gtsummary". Interactive maps were generated using R bindings to the Javascript library "Leaflet". A Bayesian regression model was fit using the R package "brms". All code for the pipeline is available in an open source repository for review and reuse by other stakeholders wishing to create their own data pipelines.

### Timeline

- At Present: Primary data collection and analysis are finished; Drafts of methods and results sections of a manuscript are finished
- By End of November: Finish full 1st draft of manuscript and seek revision feedback from advisors, then collaborators
- By End of December: Finish final draft
- By End of January: Finish submission to journal for publication

## Competencies

This culminating experience will demonstrate the following competencies for my MPH:

### Analyze quantitative and qualitative data using biostatistics, informatics, computer-based programming and software, as appropriate (Foundational #3)

As in the project description.

### Discuss the means by which structural bias, social inequities and racism undermine health and create challenges to achieving health equity at organizational, community and societal levels (Foundational #6)

As in latter paragraphs of the introduction.

### Formulate and apply plans for data cleaning and management using statistical analysis software (Generalist #10)

As in paragraphs 2-3 of the project description.

### Develop visualized data using computer-based statistical analysis package(s) (Generalist #17)

As in paragraph 4 of the project description.

### Calculate epidemiological measures of association between risk factors and disease (Generalist #20)

As in paragraph 4 of the project description.

## Citations