---
title: "Sandbox"
author: "Daniel P. Hall Riggins, MD"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
library(targets)
library(tidyverse)
library(stringr)
library(sf)
library(tidycensus)
library(lubridate)
library(gt)
```

```{r}
tar_make()
tar_load(suid)
tar_load(ccme_archive_suid_cases)
```

```{r}
summary(suid$pop_under_five)
```

```{r}
summary(sqrt(suid$pop_under_five))
```
```{r}
14.6^2
```

```{r}
scaling_factor <- (213.6/139398)
```


```{r}
DataExplorer::plot_histogram(sqrt(suid$pop_under_five))
```
```{r}
DataExplorer::plot_histogram(births$live_births)
```

```{r}
#NEW
anti_join(suid_from_tidycensus_raw, suid_from_internal_raw, by = c("fips" = "FIPS")) |> 
    arrange(fips)
```
```{r}
#OLD
anti_join(suid_from_internal_raw, suid_from_tidycensus_raw, by = c("FIPS" = "fips")) |> 
    arrange(FIPS)
```
Census Tract Changes

17031320100 -> 17031320101, 17031320102
17031330100 -> 17031330101, 17031330102, 17031330103
17031380500, 17031835900 -> 17031380600

```{r}
filter(suid, sf::st_is_empty(suid))
```


```{r}
summary(suid$approx_suid_incidence)
```

```{r}

```


```{r}
cook_tracts_2019 <-
    tigris::tracts(
        state = 17,
        county = 031,
        year = 2019
    ) |> 
    mutate(GEOID = as.numeric(GEOID))
```

```{r}
anti_join(suid_from_internal_raw, cook_tracts_2019, by = c("FIPS" = "GEOID"))
```


```{r}
ccme_archive_suid_cases |> 
    mutate(
        year_month = zoo::as.yearmon(mdy_hms(date_of_death)),
        year_quarter = zoo::as.yearqtr(mdy_hms(date_of_death))
        
    ) |> 
    group_by(year_quarter) |> 
    summarise(n = n()) |> 
    ggplot(aes(x = year_quarter, y = n)) +
    geom_point() +
    geom_line()

```

```{r}
#datapasta::df_paste()
births <-
    tibble(
       County = c("Illinois","Adams",
                  "Alexander","Bond","Boone","Brown","Bureau","Calhoun",
                  "Carroll","Cass","Champaign","Chicago",
                  "Christian","Clark","Clay","Clinton","Coles","Cook"),
       `2020` = c(133304,755,56,142,540,
                  59,339,47,135,169,2107,31087,300,181,154,
                  389,467,25020),
       `2019` = c(140145,773,63,159,565,
                  57,322,41,134,185,2233,32880,349,168,154,
                  398,493,26147),
       `2018` = c(144828,768,51,154,512,
                  65,312,37,127,170,2254,34857,360,189,157,
                  401,485,26930),
       `2017` = c(149390,815,70,147,623,
                  57,324,47,143,180,2296,36321,311,164,141,
                  428,457,28037),
       `2016` = c(154467,845,79,148,574,
                  68,350,48,138,182,2395,37999,338,180,159,
                  412,528,28760),
       `2015` = c(158101,851,84,142,567,
                  53,365,44,156,172,2400,39269,360,185,163,
                  449,531,29524),
       `2014` = c(158522,820,107,162,
                  612,56,321,53,139,174,2437,40137,316,185,163,
                  425,520,29389),
       `2013` = c(156918,845,108,168,
                  564,61,385,52,137,142,2387,39612,363,192,144,
                  403,502,29288),
       `2012` = c(159152,782,107,153,
                  561,55,332,45,140,190,2377,40985,354,212,192,
                  422,495,29250),
       `2011` = c(161234,827,108,162,
                  590,48,333,53,144,189,2398,41532,378,200,147,
                  433,514,29578),
       `2010` = c(164998,812,96,190,636,
                  44,330,55,149,173,2345,42805,355,197,166,
                  384,520,30190)
   ) |> 
    tidyr::pivot_longer(
        cols = 2:12,
        names_to = "year",
        values_to = "live_births"
    ) |> 
    filter(County == "Cook") |> 
    select(-County)
```

```{r}
vital_stats_for_cook <-
    tar_read(ccme_archive_suid_cases) |>
    mutate(year = as.character(year(mdy_hms(date_of_death)))) |>
    group_by(year) |> 
    summarise(deaths = n()) |> 
    full_join(births, by = "year") |> 
    filter(year >= 2015 & year <= 2019) |> 
    mutate(deaths_per_births = deaths / live_births * 1000) 

vital_stats_for_cook
```

```{r}
total_births_for_cook <- sum(vital_stats_for_cook$live_births)
total_deaths_for_cook <- sum(vital_stats_for_cook$deaths)
total_survivals_for_cook <- total_births_for_cook - total_deaths_for_cook
alpha_prior <- total_deaths_for_cook * est_scaling_factor
beta_prior <- total_survivals_for_cook * est_scaling_factor

est_scaling_factor <- median(suid$pop_under_five) / total_births_for_cook

prior <- alpha_prior / (alpha_prior + beta_prior)


```

```{r}
beta_ests <-
    suid |> 
    mutate(
        glm_nb_prediction = 
            insight::get_predicted(
                MASS::glm.nb(
                    suid_count ~ public_insurance + count_opioid_death + white + count_opioid_death:white,
                    data = suid
                )
            ),
        est_risk = (glm_nb_prediction + suid_count) / (glm_nb_prediction + suid_count + beta_prior + ((pop_under_five/5) - suid_count)) * 1000,
        spatial_est_risk = sfdep::st_lag(est_risk, nb = neighbors, wt = weights)
    )
```

```{r}

# Configure color palette
suid_palette <- 
    leaflet::colorNumeric(
        palette = "magma",
        reverse = TRUE,
        domain = beta_ests$spatial_est_risk
    )

leaflet::leaflet(beta_ests) |>
    # Use CartoDB's background tiles
    leaflet::addProviderTiles("CartoDB.Positron") |>
    # Center and zoom the map to Cook County
    leaflet::setView(lat = 41.816544, lng = -87.749500, zoom = 9) |>
    # Add button to enable fullscreen map
    leaflet.extras::addFullscreenControl() |>
    # Add census tract polygons colored to reflect the number of deaths
    leaflet::addPolygons(
        # No borders to the polygons, just fill
        color = "gray",
        weight = 0.25,
        opacity = 1,
        # Color according to palette above
        fillColor = ~ suid_palette(spatial_est_risk),
        # Group polygons by number of deaths for use in the layer control
        group = ~ suid_count_factor,
        # Make slightly transparent
        fillOpacity = 0.5,
        label = "Click me for more details!",
        # Click on the polygon to get its ID
        popup = 
            ~ paste0(
                "<b>FIPS ID</b>: ", as.character(fips), "</br>",
                "<b>Observed SUID</b>: ", suid_count, " death(s)</br>",
                "<b>Total Population</b>: ", pop_total, " people</br>",
                "<b>Population Under 5 Years Old</b>: ", pop_under_five, " children</br>",
                "<b>Est. Risk</b>: ", round(spatial_est_risk, 2), " deaths per 1,000 live births"
            )
    ) |>
    #Add legend
    leaflet::addLegend(
        title = "Estimated Risk of SUID<br>per 1,000 live births<br> per census tract <br> in Cook County, IL <br> from 2015-2019",
        values = ~ spatial_est_risk,
        pal = suid_palette,
        position = "topright"
    ) |>
    # Add ability to toggle each factor grouping on or off the map
    leaflet::addLayersControl(
        overlayGroups = c(
            "No Deaths", 
            "One Death", 
            "Two Deaths", 
            "Three Deaths", 
            "Four Deaths", 
            "Five Deaths", 
            "Six+ Deaths"
        ),
        position = "topleft"
    )
```






```{r}
datapasta::df_paste()


tibble(
    exposure = c("homeless", "marquette", "dog", "cat", "flea", "tick"),
    rmsf = c(10, 22, 20, 4, 2, 13),
    control = c(2, 25, 5, 10, 5, 2)
) |> 
    mutate(
        ar = round(rmsf / 25 * 100),
        or = round(ar / (control / 50 * 100), 1)
    )
```


```{r}
x <- seq(0, 1, 100)

curve(dbeta(x, total_deaths_for_cook, total_births_for_cook - total_deaths_for_cook))
```

```{r}
ggplot() +
  geom_function(fun = dbeta, args = list(shape1 = alpha_prior, shape2 = beta_prior)) +
    geom_function(fun = dbeta, args = list(shape1 = alpha_prior + 6, shape2 = beta_prior + 0), color = "blue") +
    coord_cartesian(xlim = c(0,0.1))
    
```

```{r}
sids_pop_est_and_polygons |> 
    ggplot(aes(x = avg_per_household)) +
    geom_histogram()

sd(sqrt(suid$pop_under_five))
```


```{r}
ccme_archive_suid_cases |> 
    select(auto_captured, gender, race, latino) |> 
    gtsummary::tbl_summary(by = auto_captured) |> 
    gtsummary::add_ci() |> 
    gtsummary::add_p()
```


```{r}
ccme_archive_suid_cases$latitude[ccme_archive_suid_cases$case_number == "ME2016-00123"] <- 41.77820
ccme_archive_suid_cases$longitude[ccme_archive_suid_cases$case_number == "ME2016-00123"] <- -87.61707


ccme_archive_suid_cases |> 
    filter(auto_captured == FALSE) |> 
    st_as_sf(coords = c("longitude", "latitude")) |> 
    plot()
```


```{r}
ccme_suid_per_year <-
    ccme_archive_suid_cases |> 
    group_by(year_of_death, race_ethn) |> 
    summarise(deaths = n()) |> 
    ungroup() |> 
    filter(year_of_death %in% 2015:2019) |> 
    add_row(
        year_of_death = 2016,
        race_ethn = "Other",
        deaths = 0
    ) |> 
    add_row(
        year_of_death = 2019,
        race_ethn = "Other",
        deaths = 0
    ) |> 
    add_column(
        births = c(7728, 5123, 13723, 2950, 7443, 5069, 13172, 7249, 5129, 12624, 3035, 7067, 4885, 12091, 2887, 6899, 4679, 11737, 3076, 2832)
    ) |> 
    mutate(
        deaths_per_births = deaths / births * 1E5
    )
    
```
```{r}
combined_suid <-
    ccme_suid_per_year |> 
    group_by(year_of_death) |> 
    summarise(
        births = sum(births),
        deaths = sum(deaths)
    ) |> 
    mutate(
        deaths_per_births = deaths / births * 1E5
    )
```

```{r}
combined_suid |> 
    ggplot(aes(x = as.integer(year_of_death), y = deaths_per_births)) +
    geom_line() +
    geom_point() +
    labs(
        title = "Overall Yearly Incidence of SUID cases in Cook County, IL from 2015-2021",
        x = "Year",
        y = "Deaths per 100,000 Live Births"
    ) +
    scale_x_continuous(
        breaks = 2015:2021
    ) +
    theme_linedraw()
```


```{r}
tar_load(suid)
library(see)
library(insight)
library(modelbased)
library(dplyr)
library(purrr)
library(tibble)
library(ggplot2)
```





```{r}
source("R/make_table_for_rootogram.R")
source("R/plot_rootogram.R")

model_types |> 
    map(make_table_for_rootogram) |> 
    map(plot_rootogram)
```
    


```{r}

plot_rootogram(poisson_root_tbl)

```


```{r}
ccme_suid_per_year |> 
    ggplot(aes(x = as.integer(year_of_death), y = deaths, color = race_ethn)) +
    geom_line() +
    geom_point() +
    labs(
        title = "Counts of SUID cases in Cook County, IL from 2015-2021",
        x = "Year",
        y = "Count",
        color = "Race/Ethnicity"
    ) +
    scale_x_continuous(
        breaks = 2015:2021
    ) +
    theme_linedraw()
```

```{r}
ccme_suid_per_year |> 
    ggplot(aes(x = as.integer(year_of_death), y = births, color = race_ethn)) +
    geom_line() +
    geom_point() +
    labs(
        title = "Birth Counts in Cook County, IL from 2015-2021",
        x = "Year",
        y = "Count",
        color = "Race/Ethnicity"
    ) +
    scale_x_continuous(
        breaks = 2015:2021
    ) +
    theme_linedraw()
```

```{r}
ccme_suid_per_year |> 
    ggplot(aes(x = as.integer(year_of_death), y = deaths_per_births, color = race_ethn)) +
    geom_line() +
    geom_point() +
    labs(
        title = "Yearly Incidence of SUID cases in Cook County, IL from 2015-2021",
        x = "Year",
        y = "Deaths per 100,000 Live Births",
        color = "Race/Ethnicity"
    ) +
    scale_x_continuous(
        breaks = 2015:2021
    ) +
    theme_linedraw()
```


```{r}
filter(!is.na(longitude) & !is.na(latitude)) |> 
    st_as_sf(
        coords = c("longitude", "latitude"),
        crs = 4326
    ) |> 
    plot()
```


