
```{r}
library(targets)
library(tidyverse)
library(ggdist)
library(gt)
```

```{r}
# set_variable_labels(
    #     black = "Black (%)",
    #     white = "White (%)",
    #     hispanic = "Hispanic (%)",
    #     lt_high_school = "Less than high school (%)",
    #     high_school_diploma = "High school diploma (%)",
    #     some_college = "Some college (%)",
    #     college_diploma = "College Diploma (%)",
    #     divorced_widowed_females = "Divorced, widowed females (%)",
    #     divorced_widowed_males = "Divorced, widowed males (%)",
    #     married_females = "Married females (%)",
    #     married_males = "Married males (%)",
    #     income_gt_75 = "Income greater than the 75th percentile (%)",
    #     income_lt_10 = "Income less than the 10th percentile (%)",
    #     income_lt_25 = "Income less than the 25th percentile (%)",
    #     income_lt_50 = "Income less than the 50th percentile (%)",
    #     income_lt_75 = "Income less than the 75th percentile (%)",
    #     private_insurance = "Private insurance (%)",
    #     public_insurance = "Public insurance (%)",
    #     no_insurance = "No insurance (%)",
    #     svi_household_composition_disability = "Household composition & disability (National percentile)",
    #     svi_socioeconomic = "Socioeconomic status (National percentile)",
    #     svi_minority_language = "Minority status & language (National percentile)",
    #     svi_housing_transportation = "Housing type & transportation (National percentile)",
    #     svi_summary_ranking = "SVI summary (National ranking)",
    #     pop_under_five = "Population under 5 years old (count)",
    #     count_opioid_death = "Opioid-related deaths (count)",
    #     foreign_born = "Foreign-born (%)",
    #     male = "Male (%)",
    #     employed = "Employed (%)",
    #     spanish_language = "Spanish-speaking (%)"
    # )
```


```{r}
tar_make()
tar_load(rootogram_table)
```







```{r}
rootogram_table |> 
    ggplot(
    ) +
    geom_rect(
        aes(
            ymax = sqrt_sids_count,
            ymin = 0,
            xmin = sids_count - 0.45,
            xmax = sids_count + 0.45
        ),
        stat = "identity",
        color = "black",
        fill = "gray"
    ) +
    geom_hline(
        yintercept = 0
    ) +
    theme_linedraw() +
    labs(
        title = "Distribution of the count of SIDS events \n in Cook County Census Tracts from 2015-2019",
        x = "Number of SIDS events",
        y = "sqrt(Frequency)"
    )

ggsave(
        "tables_and_figures/sids_dist.svg",
        width = 9,
        height = 6,
        units = "in"
    )
```

```{r}
rootogram_table |> 
    ggplot(
    ) +
    geom_rect(
        aes(
            ymax = sqrt_sids_count,
            ymin = 0,
            xmin = sids_count - 0.45,
            xmax = sids_count + 0.45
        ),
        stat = "identity",
        color = "black",
        fill = "gray"
    ) +
    geom_point(
       aes(
           x = sids_count,
           y = nb_expected
       ),
       color = "gold3",
       size = 1
    ) +
    geom_line(
       aes(
           x = sids_count,
           y = nb_expected
       ),
       color = "gold3",
       width = 1
    ) +
    geom_hline(
        yintercept = 0
    ) +
    theme_linedraw() +
    labs(
        title = "Distribution of the count of SIDS events \n in Cook County Census Tracts from 2015-2019",
        x = "Number of SIDS events",
        y = "sqrt(Frequency)"
    )

ggsave(
        "tables_and_figures/sids_dist_w_nb_expected.png",
        width = 9,
        height = 6,
        units = "in"
    )
```

```{r}
rootogram_table |> 
    ggplot(
    ) +
    geom_rect(
        aes(
            ymax = nb_expected,
            ymin = nb_expected - sqrt_sids_count,
            xmin = sids_count - 0.45,
            xmax = sids_count + 0.45
        ),
        stat = "identity",
        color = "black",
        fill = "gray"
    ) +
    geom_point(
       aes(
           x = sids_count,
           y = nb_expected
       ),
       color = "gold3",
       size = 1
    ) +
    geom_line(
       aes(
           x = sids_count,
           y = nb_expected
       ),
       color = "gold3",
       width = 1
    ) +
    geom_hline(
        yintercept = 0
    ) +
    theme_linedraw() +
    labs(
        title = "Distribution of the count of SIDS events \n in Cook County Census Tracts from 2015-2019",
        x = "Number of SIDS events",
        y = "sqrt(Frequency)"
    )

ggsave(
        "tables_and_figures/sids_dist_w_nb_rootogram.png",
        width = 9,
        height = 6,
        units = "in"
    )
```

```{r}
performance::performance(model_of_sids_counts)
```

```{r}
parameters::model_parameters(model_of_sids_counts) 
```
```{r}
parameters::model_parameters(model_of_sids_counts, exponentiate = TRUE) 
```

```{r}
parameters::model_parameters(model_of_sids_counts, exponentiate = TRUE, standardize = "refit") 
```


```{r}
rootogram_table |> 
    ggplot(
    ) +
    geom_rect(
        aes(
            ymax = lm_expected,
            ymin = lm_expected - sqrt_sids_count,
            xmin = sids_count - 0.45,
            xmax = sids_count + 0.45
        ),
        stat = "identity",
        color = "black",
        fill = "gray"
    ) +
    geom_point(
       aes(
           x = sids_count,
           y = lm_expected
       ),
       color = "springgreen4",
       size = 1
    ) +
    geom_line(
       aes(
           x = sids_count,
           y = lm_expected
       ),
       color = "springgreen4",
       width = 1
    ) +
    geom_hline(
        yintercept = 0
    ) +
    theme_linedraw() +
    labs(
        title = "Distribution of the count of SIDS events \n in Cook County Census Tracts from 2015-2019",
        x = "Number of SIDS events",
        y = "sqrt(Frequency)"
    )

ggsave(
        "tables_and_figures/sids_dist_w_lm_rootogram.png",
        width = 9,
        height = 6,
        units = "in"
    )
```

```{r}
performance::performance(lm_sids_model)
```

